# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d1560122e0f760742f99fe68ca38dc5121f749c81cd1f1b7dd0605258f725a9a01e35839c6673fb33c22a701c2ebfb7a04cb4a19cf35fd809cb86a23cd77971

test:
  secret_key_base: 9d26c1732d35b83933bab7b5ddf6c9e95d3959c73bfab21022fdffdb32def367862567e67004ae91efde26f3a477dd8a9e51e5c71391c707500fa19e73f6a1ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
